version: '3'

services:
  postgres:
    container_name: userlogin_postgres
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbgochat
    volumes:
      - "dbdata:/var/lib/postgresql/go-chat/data"

  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - "8000:8080"

volumes:
  dbdata:
